apiVersion: apps/v1
kind: Deployment
metadata:
  name: ${{values.name | dump}}
  namespace: default
  labels:
    entity-id: ${{values.name}}
    app: ${{values.name}}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ${{values.name}}
  template:
    metadata:
      labels:
        app: ${{values.name}}
        entity-id: ${{values.name}}
    spec:
      containers:
        - name: ${{values.name}}
          image: ${{values.image}}
          ports:
            - containerPort: 80
